import { Amplify } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import '../styles/globals.css';
import type { AppProps } from 'next/app';
import awsExports from '../aws-exports';
import { Layout } from '../components/layout';
import Head from 'next/head';

Amplify.configure(awsExports);

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      {/* // <h1>Hello {user.username}</h1>
      // <button onClick={signOut}>Sign out</button> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default withAuthenticator(App);
